
- name: install python on target machines
  raw: which python3 || (apt --yes update && apt install --yes {{ lxc_infrastructure_python_packages | join(' ') }})

- name: update the /etc/ssh/sshd_config file
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^UseDNS"
    line: "UseDNS no"
    insertafter: EOF
    state: present
  notify:
    - restart ssh

- name: install sudo
  package:
    name: sudo
    update_cache: yes
