---
- name: waiting for ssh port to be available
  connection: local
  wait_for:
    host: "{{ ansible_host }}"
    port: 22

- name: ssh known hosts are up-to-date locally
  connection: local
  known_hosts:
    state: absent
    name: "{{ inventory_hostname }}"
    path: "{{ lxc_infrastructure_user_ssh_dir }}/known_hosts"
  failed_when: no
